oro_entity:
    entity_aliases:
        Marello\Bundle\InventoryBundle\Entity\InventoryLevel:
            alias: marelloinventorylevel
            plural_alias: marelloinventorylevels

        Marello\Bundle\InventoryBundle\Entity\BalancedInventoryLevel:
            alias: marellobalancedinventorylevel
            plural_alias: marellobalancedinventorylevels
