marelloenterprise_inventory_warehouse_api:
    resource:     "@MarelloEnterpriseInventoryBundle/Controller/Api/Rest/WarehouseController.php"
    type:         rest

marelloenterprise_inventory_warehousegroup_api:
    resource:     "@MarelloEnterpriseInventoryBundle/Controller/Api/Rest/WarehouseGroupController.php"
    type:         rest

marelloenterprise_inventory_warehousechannelgrouplink_api:
    resource:     "@MarelloEnterpriseInventoryBundle/Controller/Api/Rest/WarehouseChannelGroupLinkController.php"
    type:         rest

marelloenterprise_inventory_wfarule_api:
    resource:     "@MarelloEnterpriseInventoryBundle/Controller/Api/Rest/WFARuleController.php"
    type:         rest
