services:
    marello_payment_term.provider.payment_term:
        class: 'Marello\Bundle\PaymentTermBundle\Provider\PaymentTermProvider'
        arguments:
            - '@oro_config.manager'
            - '@oro_entity.doctrine_helper'
