api:
    entities:
        Marello\Bundle\SupplierBundle\Entity\Supplier:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: false
