marelloenterprise_instoreassistant_rest_api_authenticate_instore_user:
    path: /api/instoreuserapi/authenticate
    methods: [PUT]
    defaults:
        _controller: MarelloEnterpriseInstoreAssistantBundle:Api\InstoreAssistantUser:authenticate
        _action: authenticate
    options:
        group: rest_api

# returns a response with CORS headers if a CORS pre-flight call otherwise it will return the 'default';
# either a 405 METHOD NOT ALLOWED or 200 with meta data
marelloenterprise_instoreassistant_rest_api_cors_options_list:
    path: /api/{entity}
    methods: [OPTIONS]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: MarelloEnterpriseInstoreAssistantBundle:Api\CorsOptions:options
        _action: options
    options:
        group: rest_api
        priority: -10

marelloenterprise_instoreassistant_rest_api_cors_options_single:
    path: /api/{entity}/{id}
    methods: [OPTIONS]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    defaults:
        _controller: MarelloEnterpriseInstoreAssistantBundle:Api\CorsOptions:options
        _action: options
    options:
        group: rest_api
        priority: -10